image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-example-microservice:
  stage: build
  script:
    gradle example-microservice:assemble example-microservice:testClasses

checkStyle-example-microservice:
  stage: staticAnalysis
  script:
    gradle example-microservice:checkstyleMain example-microservice:checkStyleTest
  allow_failure: true


PMD-example-microservice:
  stage: staticAnalysis
  script:
    gradle example-microservice:pmdMain
  allow_failure: true

test-example-microservice:
  stage: test
  script:
    - gradle example-microservice:test example-microservice:jacocoTestReport
    - cat example-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
