include:
  - authentication-microservice/.gitlab-ci.yml
  - example-microservice/.gitlab-ci.yml
  - activity-microservice/.gitlab-ci.yml
  - users-microservice/.gitlab-ci.yml
  - activity-microservice/.gitlab-ci.yml
  - notifications-microservice/.gitlab-ci.yml
