package nl.tudelft.sem.project.notifications;

public enum EventType {

    RESET_PASSWORD, SIGN_UP, ACTIVITY_FULL, REJECT_REGISTRATION,JOINED_ACTIVITY, USER_JOINED, USER_LEFT, ACTIVITY_START_SOON, TEST, TEST_ACTIVITY

}
