package nl.tudelft.sem.project.notifications;

public enum EventType {
    RESET_PASSWORD, SIGN_UP, ACTIVITY_FULL, JOINED_ACTIVITY, USER_JOINED, USER_LEFT,
    ACTIVITY_START_SOON, TEST, TEST_ACTIVITY, CREATED_ACTIVITY, RESET_PASSWORD_CONFIRM
}
