image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-notifications-microservice:
  stage: build
  script:
    gradle notifications-microservice:assemble notifications-microservice:testClasses

checkStyle-notifications-microservice:
  stage: staticAnalysis
  script:
    gradle notifications-microservice:checkstyleMain notifications-microservice:checkStyleTest
  allow_failure: true


PMD-notifications-microservice:
  stage: staticAnalysis
  script:
    gradle notifications-microservice:pmdMain
  allow_failure: true

test-notifications-microservice:
  stage: test
  script:
    - gradle notifications-microservice:test notifications-microservice:jacocoTestReport
    - cat notifications-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
